// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SycamoreCommercial.Data;

#nullable disable

namespace SycamoreCommercial.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250530074555_configuringdatabase")]
    partial class configuringdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SycamoreCommercial.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Table",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Security",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Abdullah",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "BhaadeDada",
                            Order = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
